version: '3'

services:
    php56:
        container_name: php56
        image: hendra1992/php_56
        restart: always
        volumes:
            - "./php/v5.6/htdocs:/var/www/html"
        ports:
            - 5656:80
            - 553:443
        links:
            - mysql56
            - mysql57
            - pgsql93
            - pgsql96
            - mongo
    php72:
        container_name: php72
        image: hendra1992/php_72
        restart: always
        volumes:
            - "./php/v7.2/htdocs:/var/www/html"
        ports:
            - 7272:80
            - 773:443
        links:
            - mysql56
            - mysql57
            - pgsql93
            - pgsql96
            - mongo
    mysql56:
        container_name: mysql56
        image: mysql:5.6.42
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: anugerah
            MYSQL_DATABASE: mysql
        ports:
            - "3307:3306"
        volumes:
            - "./database/mysql/my.conf:/etc/mysql/conf.d/config-file.cnf"
            - "./database/mysql/data/v5.6.42:/var/lib/mysql:rw"
    mysql57:
        container_name: mysql57
        image: mysql:5.7.24
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: anugerah
            MYSQL_DATABASE: mysql
        ports:
            - "3308:3306"
        volumes:
            - "./database/mysql/my.conf:/etc/mysql/conf.d/config-file.cnf"
            - "./database/mysql/data/v5.7.24:/var/lib/mysql:rw"
    pgsql93:
        container_name: pgsql93
        image: postgres:9.3.23
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: anugerah
            POSTGRES_DB: postgres
        ports:
            - "5433:5432"
    pgsql96:
        container_name: pgsql96
        image: postgres:9.6.10
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: anugerah
            POSTGRES_DB: postgres
        ports:
            - "5434:5432"
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=anugerah
        ports:
            - "27018:27017"
        volumes:
            - "./database/mongodb/data:/data/db"
        command: mongod